

import torch
from torch import Tensor 
import numpy as np
import os
import torch
from rdkit import Chem

def save_tensor_to_xyz(positions: Tensor, atom_types: list[str], anchor_mask: Tensor, file_path: str):
    """
    Save positions to an XYZ file with specified atom types and highlighted anchor atoms.

    :param positions: Tensor of atom positions.
    :param atom_types: List of atom types corresponding to each atom in the positions.
    :param anchor_mask: Tensor indicating which atoms are anchor atoms.
    :param file_path: The path to the file where the XYZ data will be saved.
    """
    positions = positions.cpu().numpy()
    anchor_mask = anchor_mask.cpu().numpy()

    num_atoms = positions.shape[0]

    with open(file_path, 'w') as file:
        file.write(f"{num_atoms}\n")
        file.write("Generated by apply_transform\n")
        for i, pos in enumerate(positions):
            atom_type = atom_types[i]
            if anchor_mask[i]:
                atom_type = f"Hg "
            file.write(f"{atom_type} {pos[0]} {pos[1]} {pos[2]}\n")

    print(f"XYZ file saved to {file_path}")



def save_agent_dict_to_xyz(agent_dict, output_file):
    """
    Save all agents in agent_dict to a single XYZ file, with total atom count and coordinates only.

    Args:
        agent_dict (dict): A dictionary containing agent data.
        output_file (str): Path to the output XYZ file.
    """
    #print("agent_dict", agent_dict)
    output_dir = os.path.dirname(output_file)
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    total_atoms = sum(agent_data.atomic_numbers.shape[0] for agent_data in agent_dict.values())
    all_xyz_content = f"{total_atoms}\n\n"

    for agent_name, agent_data in agent_dict.items():
        # Extract atomic numbers and positions
        atomic_numbers = agent_data.atomic_numbers
        positions = agent_data.pos

        if not isinstance(atomic_numbers, torch.Tensor) or not isinstance(positions, torch.Tensor):
            raise ValueError(f"Invalid data for agent {agent_name}: Expected tensors for atomic_numbers and positions.")

        if atomic_numbers.shape[0] != positions.shape[0]:
            raise ValueError(f"Mismatch in sizes for agent {agent_name}: {atomic_numbers.shape[0]} atoms vs {positions.shape[0]} positions.")

        # Convert atomic numbers to element symbols
        elements = [atomic_number_to_element(num.item()) for num in atomic_numbers]

        for element, pos in zip(elements, positions):
            all_xyz_content += f"{element} {pos[0]:.6f} {pos[1]:.6f} {pos[2]:.6f}\n"

    # Write all data to the XYZ file
    with open(output_file, "w") as f:
        f.write(all_xyz_content)

    print(f"All agents saved to single .xyz file: {output_file}")

def atomic_number_to_element(atomic_number):
    """
    Converts an atomic number to its corresponding element symbol using RDKit.

    Parameters:
        atomic_number (int): Atomic number of the element.

    Returns:
        str: Element symbol.
    """
    periodic_table = Chem.GetPeriodicTable()
    return periodic_table.GetElementSymbol(atomic_number)
