activation: relu
agent_type: chain
anchor_graph_sphere: false
angle_encoding_repr_learning: false
architecture: e3nn
batch_norm: batch_norm
bl_sigma_max: 0.0011
bl_sigma_min: 0.001
calc_permute_rmsd: false
center_complex: true
center_dist_emb_dim: 64
center_max_radius: 30.0
config: paper/score_model_tmqmg/config_train.yml
cross_cutoff_threshold: 5.0
cross_dist_emb_dim: 64
cross_max_neighbors: 30
cross_max_radius: 30.0
cutoff_lower: 0.0
cutoff_upper: 5.0
data_dir: "./data"
debug: false
debug_performance: false
deviation_eps: 0.1
distance_emb_dim: 64
distributed: false
dropout_p: 0.1
dynamic_max_cross: false
edge_fdim: 0
ema_decay_rate: 0.999
embed_scale: 10000
embed_type: sinusoidal
enable_plotting: true
enforce_stability: false
eval_every: 3
featurizer: base
first_break: 0.0
grad_clip_value: 0.8
group_name: tmqmg
hidden_channels: 128
inference_every: 10
inference_goal: max
inference_metric: val_loss
inference_multiplicity: 1
inference_steps: 20
job_type: null
joint_rot_sphere_update: false
keep_core_rigid: false
last_break: 6.0
load_temp_config_path: ''
log_dir: logs
log_every: 5
lr: 0.0001
lr_sched_metric: val_loss
lr_sched_metric_goal: min
max_neighbors: 30
max_radius: 5
max_sphere_add_radius: 0.0
model: score
n_conv_layers: 1
n_deviations: 0
n_epochs: 5000
n_gpus: 0
n_s: 6
n_v: 2
no_rot_all_ligands: false
no_rot_first_lig: true
no_sphere_first_lig: false
no_torsion: false
no_val_before_training: true
node_encoder_type: base
node_fdim: 132
notes: null
num_bins: 20
num_inference_complexes: 5
num_layers: 6
num_rbf: 16
num_temp_iterations: 100
num_workers: 12
ode: true
optim_name: adam
partially_rigid: true
pert_strategy: all-but-one
predict_sphere_direction: true
predict_x0_sphere: false
print_flush_only: true
project_name: tmqmg_sphere
random_init_missing_keys: false
resolution: c_alpha
restrict_rot_update: false
rot_center_anchor: true
rot_sigma_max: 1.65
rot_sigma_min: 0.02
run_name: tmqmg_sphere_validate_separate_sphere_rot_global_pred_anchor-7jo6a08g-q0zbwl8o-ub0imv3q
same_t_for_agent: true
save_for_confidence: false
save_for_confidence_interval: 20
scale_by_sigma: true
scale_sphere: false
scheduler: plateau
scheduler_goal: max
scheduler_mode: min
scheduler_patience: 10
separate_intra_inter_agent_updates: false
separate_rot_sphere_conv: true
sh_lmax: 2
sigma_emb_dim: 32
sphere_diffusion: true
sphere_projection: true
sphere_sigma_max: 1.55
sphere_sigma_min: 0.08
step_every: 6
temp_psi: ''
temp_sampling: ''
temp_sigma_data: ''
temp_sweep: false
time_embed_scale: 10000
time_embed_type: sinusoidal
timepoints_per_complex: 1
tor_sigma_max: 3.14
tor_sigma_min: 0.0314
tr_sigma_max: 1
tr_sigma_min: 0.01
train_bs: 16
train_complex_dir: complexes
train_complex_list_file: complexes-train.txt
train_dataset: tmqmg
train_size_sorted: false
trainable_rbf: false
transform: ma_noise
use_distogram: false
use_distributed: false
use_temp_effects: false
val_bs: 32
val_complex_dir: null
val_complex_list_file: complexes-train.txt
val_dataset: null
val_size_sorted: false
w_bl: 0
w_dist: 1.0
w_distogram: 1.0
w_rot: 1
w_sphere: 2
w_tor: 1
w_tr: 0.0
wandb_dir: null
wandb_entity: null
wandb_mode: online
weight_decay: 0.0

